"""Configuration module for values shared throughout the project."""

from .settings import (
    BASE_PATH, CONFIG_PATH, TESTS_PATH, UTILS_PATH, DATA_PATH, FIGURES_PATH, NOTEBOOKS_PATH,
    RAW_DATA_PATH, PROCESSED_DATA_PATH, FINAL_DATA_PATH, RAW_FIGURES_PATH, PROCESSED_FIGURES_PATH,
    FINAL_FIGURES_PATH, H_PALETTE
)


__all__ = [
    "BASE_PATH", "CONFIG_PATH", "TESTS_PATH", "UTILS_PATH", "DATA_PATH",
    "FIGURES_PATH", "NOTEBOOKS_PATH", "RAW_DATA_PATH", "PROCESSED_DATA_PATH",
    "FINAL_DATA_PATH", "RAW_FIGURES_PATH", "PROCESSED_FIGURES_PATH",
    "FINAL_FIGURES_PATH", "H_PALETTE"
]
